# Generated by Django 2.2.6 on 2019-11-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20191125_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(max_length=120),
        ),
    ]
