# Generated by Django 2.2.6 on 2019-12-22 02:54

from django.db import migrations, models
import fichas.models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='numero_folio',
            field=models.BigIntegerField(default=fichas.models.Ficha.number),
        ),
    ]
