# Generated by Django 2.2.6 on 2019-12-22 03:21

from django.db import migrations, models
import fichas.models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_ficha_numero_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='numero_folio',
            field=models.BigIntegerField(default=fichas.models.Ficha.number),
        ),
    ]
