# Generated by Django 2.2.6 on 2019-12-22 03:24

from django.db import migrations, models
import fichas.models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_auto_20191222_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='numero_folio',
            field=models.BigIntegerField(default=fichas.models.Ficha.number, unique=True),
        ),
    ]
