# Generated by Django 2.2.6 on 2019-12-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='has_previously_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
